eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${CONFIG_SERVER_URL:http://localhost:8761/eureka}
