eureka:
  instance:
    hostname: ${CONFIG_SERVER_URL:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${CONFIG_SERVER_URL:localhost}:8761/eureka
